Repository app-dojo-salon/LeanjoyFC-TodoApp, pull requests merged in 2020-09, with the labels that each got.

#5 Pull Requestの記入テンプレートの作成
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feature

#6 BaseのList画面を作成
  TodoApp.xcodeproj/project.pbxproj
  TodoApp/Base.lproj/Main.storyboard
  TodoApp/Info.plist
  TodoApp/ViewController.swift
  TodoApp/Views/Controllers/ItemListViewController.swift
  TodoApp/Views/ItemList.storyboard
  TodoApp/Views/ItemListTableViewCell.swift
  TodoApp/Views/ItemListTableViewCell.xib
Labels: feature

#10 Add画面の作成 & テストデータの作成/表示
  .gitignore
  TodoApp.xcodeproj/project.pbxproj
  TodoApp/Views/Controllers/ItemAddViewController.swift
  TodoApp/Views/Controllers/ItemListViewController.swift
  TodoApp/Views/ItemAdd.storyboard
  TodoApp/Views/ItemList.storyboard
Labels: feature

#23 Add画面とList画面を連携2
  TodoApp/Assets.xcassets/check.imageset/Contents.json
  TodoApp/Assets.xcassets/check.imageset/check.png
  TodoApp/Assets.xcassets/check.imageset/check@2x.png
  TodoApp/Assets.xcassets/check.imageset/check@3x.png
  TodoApp/Views/Controllers/ItemAddViewController.swift
  TodoApp/Views/Controllers/ItemListViewController.swift
  TodoApp/Views/ItemListTableViewCell.swift
  TodoApp/Views/ItemListTableViewCell.xib
Labels: feature

#24 Realmの準備
  Podfile
  Podfile.lock
  TodoApp.xcodeproj/project.pbxproj
  TodoApp.xcworkspace/contents.xcworkspacedata
  TodoApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  TodoApp/Models/items.swift
  TodoApp/Views/Controllers/ItemAddViewController.swift
  TodoApp/Views/Controllers/ItemListViewController.swift
Labels: feature

#29 重複していた処理を修正、他Code修正
  TodoApp.xcodeproj/project.pbxproj
  TodoApp/Identifier/IdentifierType.swift
  TodoApp/Models/items.swift
  TodoApp/Views/Controllers/ItemAddViewController.swift
  TodoApp/Views/Controllers/ItemListViewController.swift
Labels: improvement

#27 Add画面とList画面を連携2 の続き
  TodoApp/Views/Controllers/ItemListViewController.swift
Labels: feature

#31 RealmSwiftのバージョン修正
  Podfile
  Podfile.lock
Labels: bug
